2021-05-09 10:55:49,686 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 10:55:49,687 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-09 10:55:49,687 INFO    MainThread:14540 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_105549-2orxgk2i\logs\debug.log
2021-05-09 10:55:49,687 INFO    MainThread:14540 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_105549-2orxgk2i\logs\debug-internal.log
2021-05-09 10:55:49,688 INFO    MainThread:14540 [wandb_init.py:init():369] calling init triggers
2021-05-09 10:55:49,688 INFO    MainThread:14540 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 600, 'learningRate': 0.0001, 'batchSize': 128, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': True}
2021-05-09 10:55:49,688 INFO    MainThread:14540 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 1mtbzctc
2021-05-09 10:55:49,691 INFO    MainThread:14540 [wandb_run.py:finish():1197] finishing run tecai/MLP/1mtbzctc
2021-05-09 10:55:49,694 ERROR   MainThread:14540 [jupyter.py:save_history():312] Run pip install nbformat to save notebook history
2021-05-09 10:55:49,694 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:55:49,694 INFO    MainThread:14540 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-09 10:55:49,694 INFO    MainThread:14540 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-09 10:55:49,695 INFO    MainThread:14540 [wandb_run.py:_restore():1496] restore
2021-05-09 10:55:49,704 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3839
  total_bytes: 3839
}

2021-05-09 10:55:54,827 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: None
2021-05-09 10:55:59,950 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: None
2021-05-09 10:56:05,068 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: None
2021-05-09 10:56:10,189 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: None
2021-05-09 10:56:15,301 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: None
2021-05-09 10:56:20,414 INFO    MainThread:14540 [wandb_init.py:init():418] starting backend
2021-05-09 10:56:20,414 INFO    MainThread:14540 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-05-09 10:56:20,419 INFO    MainThread:14540 [backend.py:ensure_launched():123] starting backend process...
2021-05-09 10:56:20,534 INFO    MainThread:14540 [backend.py:ensure_launched():127] started backend process with pid: 8776
2021-05-09 10:56:20,534 INFO    MainThread:14540 [wandb_init.py:init():423] backend started and connected
2021-05-09 10:56:20,537 INFO    MainThread:14540 [wandb_init.py:init():465] updated telemetry
2021-05-09 10:56:20,538 INFO    MainThread:14540 [wandb_init.py:init():484] communicating current version
2021-05-09 10:56:22,022 INFO    MainThread:14540 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-09 10:56:22,024 INFO    MainThread:14540 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-09 10:56:22,491 INFO    MainThread:14540 [wandb_init.py:init():522] starting run threads in backend
